### ISSUE TITLE
Context as Interface

### ISSUE THREAD

**Issue by yeganehaym** [alexandre-spieser/mongodb-generic-repository#1]
why didn't you consider context as an interface?
because i think if you consider it as an interface
it will decoupling and decrease dependencies and you can do unit testing and mocking

im rookie and plz clear me if i am wrong

**Comment by alexandre-spieser** [comment]
`Yes is is possible to have one, it's a relatively simple one:

```
    public interface IMongoDbContext
    {
        /// <summary>
        /// The private GetCollection method
        /// </summary>
        /// <typeparam name="TEntity"></typeparam>
        /// <returns></returns>
        IMongoCollection<TEntity> GetCollection<TEntity>();
    }
```

**Comment by yeganehaym** [comment]
another qustion?
why we use T symbol?
why dont we make different repo for product,Car,Flower,Phone and other repos for each one of them?
when is was using ef, i used those things

**Comment by alexandre-spieser** [comment]
Because it must be generic and you do not need to have one repo for each document type. 
Having 1 repo per entity is also a solution but then you need to create several repos that all do the same things (Repo<Car>, Repo<Flower>, Repo<Phone >).
The aim of the proposed repo is to handle several collections without creating one instance of the repo per collections.
It reduces development time (less code to write, so less to maintain), dependency injection (less objects to resolve and build).
