### ISSUE TITLE
GridFS (Query)

### ISSUE THREAD

**Issue by pieman302** [alexandre-spieser/mongodb-generic-repository#6]
Will the generic repository in its current guise support GridFS? If it does, could you possibly provide a sample of code time permitting.

I am looking to store binary data which in the main I will restrict to files of less than 10MB which can be stored in a standard document without issue. However, I am looking at users submitting multiple files which as part of the 'submit' process I create an archive of all these files - stamp them and store as a single zip file. In doing this I can potential exceed the maximum document size allowed. 

GridFS would support this scenario. To be honest, I could change this mechanism to say zip on the fly when the request for a specific user submission containing multiple files is made or potentially create a home grown mechanism utilising 'chunking' however based on my limited understanding of Mongo this is what GridFS does under the hood anyways.

Thoughts?

Thanks.

**Comment by alexandre-spieser** [comment]
Hi, 

I have not tested this, but since the repo is using the latest driver you should be able to perform GridFs queries.

The `IMongoDatabase` interface is exposed in the interface `IMongoDbContext` with the `Database` property which is accessible to anything inheriting the base class `BaseMongoRepository` through the property:

```
        /// <summary>
        /// The MongoDbContext
        /// </summary>
        protected IMongoDbContext MongoDbContext
```

So in your repository implementation inheriting BaseMongoRepository, you should be able to get your bucket like so:

```
var bucket = new GridFSBucket(MongoDbContext.Database, new GridFSOptions
{
    BucketName = "videos",
    ChunkSizeBytes = 1048576, // 1MB
    WriteConcern = WriteConcern.Majority,
    ReadPreference = ReadPeference.Secondary
});
```

**Comment by pieman302** [comment]
Thanks for the advice, appreciated :-)

**Comment by alexandre-spieser** [comment]
No worries :)
